### ISSUE TITLE
Add compile-time parameter checking for _MSG macros

### ISSUE THREAD

**Issue by JeffMill** [microsoft/wil#369] opened 2023-09-27 04:53 UTC
Here’s something I came up with.

Changing:

```C++
#define LOG_WIN32_MSG(win32err, fmt, ...)                       __R_FN(Log_Win32Msg)(__R_INFO(#win32err) win32err, fmt, ##__VA_ARGS__)
```

To:

```C++
#define LOG_WIN32_MSG(win32err, fmt, ...)                       \
    (void)(0 && printf(fmt, __VA_ARGS__)); \
    __R_FN(Log_Win32Msg)(__R_INFO(#win32err) win32err, fmt, ##__VA_ARGS__)
```

provides compile-time safety for _MSG macros.  The `(0 && ...` should make it so it doesn't emit any code (when optimized), but the compiler will still to the printf check and validate args.

**Given:**

```C++
    std::error_code ec;
    std::filesystem::copy_file("c:\\src", "c:\\dst", std::filesystem::copy_options::update_existing, ec);
    if (ec)
    {
        LOG_WIN32_MSG(ec.value(), "copy_file failed: %ws (%hs)", L"c:\\src", ec.message());
    }
```

**Before:**

Compiles fine.

**After:**

Gives compile-time warning.

`d:\temp\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.cpp(24,9): warning C4477: 'printf' : format string '%hs' requires an argument of type 'char *', but variadic argument 2 has type 'std::string'`

**Comment by dunhor** [comment] 2023-09-27 05:00
This will not work. The `LOG_*` macros evaluate to an expression that invokes a function that returns a value. E.g. this would break code like:
```c++
auto hr = LOG_IF_FAILED(expr);
```

**Comment by dunhor** [comment] 2023-09-27 05:16
Also, in case someone does come up with a clever idea to get it to work, you'd want to use `wprintf`, not `printf`

**Comment by dmachaj** [comment] 2023-09-27 16:40
Would it work if the order was flipped so the expression still returns a value and the semicolon creates a new statement with the compile checking?

**Comment by dunhor** [comment] 2023-09-27 16:49
That would make it better, but wouldn't cover all scenarios. E.g.
```c++
if (auto hr = LOG_IF_FAILED(expr); hr == E_OUTOFMEMORY) { ... }
```

**Comment by JeffMill** [comment] 2023-09-27 19:25
**Perfect is the enemy of good enough. **

Even if this doesn't handle some of the explicit LOG_IF* cases, it still would be a huge will to handle the *_MSG cases.  If all cases can be covered, that's great.

**Comment by dunhor** [comment] 2023-09-27 20:00
The problem isn't that we want to be perfect. The problem is introducing a source breaking change.

Ultimately, I'm unsure of how impactful this might be. The "eye test" suggests that it _could_ be untenable, but until someone attempts to build the entirety of Windows with such a change, nobody can say for certain.

Side note: adding a dependency on `wprintf` _might_ also have other issues (though I get the feeling that's _probably_ unlikely). We could instead "invoke" a locally declared function that uses `_Printf_format_string_`, although internet sleuthing suggests that produces a _different_ warning that might not always be surfaced.

**Comment by dunhor** [comment] 2023-09-27 20:04
Drats, yeah, the compiler does not, by default, analyze `_Printf_format_string_` like I was hoping it would: https://godbolt.org/z/exoY8ahEr

**Comment by dunhor** [comment] 2023-09-27 21:58
On second thought, we're making this too complicated. We can easily incorporate the "check" into the function invocation. E.g.
```c++
#define __WI_MSG_FMT_STRING(fmt, ...)                        (1 || ::wprintf(L"" fmt, ##__VA_ARGS__)) ? fmt : nullptr
...
#define LOG_HR_MSG(hr, fmt, ...)                                __R_FN(Log_HrMsg)(__R_INFO(#hr) wil::verify_hresult(hr), __WI_MSG_FMT_STRING(fmt, ##__VA_ARGS__), ##__VA_ARGS__)
```

```c++
LOG_CAUGHT_EXCEPTION_MSG("Test: %s", "foo"); // warning C4477: 'wprintf' : format string '%s' requires an argument of type 'wchar_t *', but variadic argument 1 has type 'const char *'

LOG_CAUGHT_EXCEPTION_MSG("Test: %s", std::string("bar")); // warning C4477: 'wprintf' : format string '%s' requires an argument of type 'wchar_t *', but variadic argument 1 has type 'std::string'
```
https://github.com/microsoft/wil/compare/master...dunhor/msgwarn

I'm still unsure how "safe" it is to reference `wprintf`. If we try this out, we need to try it out in the OS.

**Comment by dunhor** [comment] 2023-09-27 22:09
Looking closer, it looks like we already include `strsafe.h`, which includes `stdio.h` (among other things), so my concerns are probably unfounded and anyone who might have issues are probably already being excluded by the `__WIL_MIN_KERNEL` etc. checks.

**Comment by dunhor** [comment] 2023-09-27 22:21
Hmm, one major issue. While there's no binary size difference for MSVC, there is one for Clang
```
               release      debug
before(msvc):  23,486,464   35,736,576
after(msvc):   23,486,464   35,736,576
before(clang): 19,547,136   20,995,072
after(clang):  19,565,568   21,013,504
```

**Comment by dmachaj** [comment] 2023-09-27 22:25
18KB (a fraction of a percent) doesn't seem _major_.  Minor to moderate, maybe.

Does Clang have an equivalent to SizeBench to see where the differences lie?

**Comment by dmachaj** [comment] 2023-09-27 22:28
One concern I have with those macros is that we would evaluate the __VA_ARGS twice.  That could have side-effects if it is not an expression that can be safely run multiple times.

For example:
`RETURN_IF_FAILED_MSG(DoThing(), "%hs is wrong", ComputeExpensiveString());`

Somewhat contrived example but it can be a problem to double-evaluate macro parameters.

**Comment by dunhor** [comment] 2023-09-27 22:30
Right now I'm just comparing the "normal" test executable from this repo. Idk what the impact would be under more "normal" circumstances. Currently, I'm wondering if it's related to the linker - I believe CMake uses `lld-link` for Clang by default. I'm going to switch to `link.exe` to see if there's still an impact.

> Does Clang have an equivalent to SizeBench to see where the differences lie?

Well, so `link.exe` would presumably still produce PDBs that are readable by SizeBench. Idk if `lld-link` does, too.

> One concern I have with those macros is that we would evaluate the __VA_ARGS twice

It shouldn't. The arguments to `wprintf` should not get evaluated unless the first condition is false (it's not)

**Comment by dunhor** [comment] 2023-09-27 22:34
Okay, it is `lld-link`'s fault. Idk why it doesn't realize that it can discard the strings

**Comment by dunhor** [comment] 2023-09-27 22:43
To answer your other question: 
![image](https://github.com/microsoft/wil/assets/40036384/0402d8cc-7875-4316-9d5f-c090c18a82f0)

**Comment by dunhor** [comment] 2023-09-27 22:54
Although curiously enough, `strings -u` does not seem to find these new strings, so I'm not convinced that this is the issue. In that case, I'm quite uncertain what the issue is then... If it were failing to optimize out the `wprintf` path, I would expect the strings to be in the executable...

**Comment by dmachaj** [comment] 2023-09-27 22:56
[guess] Maybe it is a fixed cost to link in some sort of stub for `wprintf`...?  16KB out of a 20MB binary makes me think "fixed cost" rather than "scales with the number of macros".

**Comment by dunhor** [comment] 2023-09-27 23:04
I don't think it's a fixed cost - just fixed across release vs debug. I built the 'cpplatest' tests and the size increase was different (albeit less, for whatever crazy reason)

**Comment by dunhor** [comment] 2023-09-28 05:01
I looked at a single `LOG_CAUGHT_EXCEPTION`, so not the largest sample size, but both before and after the assembly looks the same:
```asm
witest!C_A_T_C_H_T_E_S_T_4+0x90ef [G:\wil\tests\ResultTests.cpp @ 308]:
00007ff6`5718c4af 488b8d68110000  mov     rcx,qword ptr [rbp+1168h]
00007ff6`5718c4b6 c74424202a000000 mov     dword ptr [rsp+20h],2Ah
00007ff6`5718c4be 4c8d0543ce6c00  lea     r8,[witest!`string' (00007ff6`57859308)]
00007ff6`5718c4c5 4c8d0d99ce6c00  lea     r9,[witest!`string' (00007ff6`57859365)]
00007ff6`5718c4cc ba34010000      mov     edx,134h
00007ff6`5718c4d1 e86a210000      call    witest!wil::details::in1diag3::Log_CaughtExceptionMsg (00007ff6`5718e640)
00007ff6`5718c4d6 0f28742420      movaps  xmm6,xmmword ptr [rsp+20h]
```
I was curious if the ternary operator confused the optimizer, but, at least in this specific instance, that doesn't appear to be the case. What's also wild is that if I do the simplest thing and replace with `(true ? fmt : fmt)`, the size _still_ increases, but by less. I tried switching to the comma operator among a few other things and the size seems to always increase by different amounts.

Given that it doesn't appear like the code-gen is different _and_ it doesn't appear as though the strings are making it into the binary _and_ given that `lld-link` consistenly produces smaller binaries in general _and_ given that `link.exe` seems to be unphased by the additions, I think this is probably fine

**Comment by dunhor** [comment] 2023-09-28 17:58
I'm still slightly concerned that there could be issues if the format string is not a string literal (which is a _separate_ issue). I'm going to try this out in the OS repo - PR 9647759

**Comment by dunhor** [comment] 2023-10-20 16:44
I'm going to close this out since this has been submitted to the OS repo and should be available in the next sync (hopefully next week)

**Closed by dunhor** 2023-10-20 16:44 UTC
Labels: feature-request
